chore(TDI-48973): Fix Sonar NoClassDefFoundError (#973)
https://jira.talendforge.org/browse/TDI-48973

Following SFT bump of Sonar in 9.6, builds are failing with:
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/LinkedListMultimap$1KeySetImpl

This is linked to a bug on 9.6 using Sonar cache.

It is fixed in 9.7.1, however there is another blocker for SFT to stay on version 9.6 for the time being.

(cherry picked from commit ae8af3784726d643e64a030b880c63e37a7764d7)